name: 'CapRover Deploy Image'
description: 'Action to deploy docker images to Caprover server'
author: 'Hazeezet'

branding:
    icon: upload-cloud
    color: yellow

inputs:

    server:
        description: 'CapRover admin panel URL. Example: https://captain.root.domain.com'
        required: true
        
    app-token:
        description: 'CapRover app token. using a token is better than using your password.'
        required: true

    app-name:
        description: 'Application name on the CapRover server. Your app must exists.'
        required: true

    registry-host:
        description: 'You docker registry url Example: registry.gitlab.com/username/caprover-docker-images. this is used to store image temporarily before deploying'
        required: true

    registry-user:
        description: 'Docker registry token. using a token is better than using your password.'
        required: true

    registry-token:
        description: 'Docker registry token. using a token is better than using your password.'
        required: true

    save-image:
        description: 'Permanentely save docker image to your registry'
        required: false
        default: false

    content:
        description: 'Project folder path to use to create the image'
        required: true

    dockerfile:
        description: 'Docker file path of your project'
        required: true

    image-name:
        description: 'Image name in your registry'
        required: true

    image-tag:
        description: 'New image tag'
        required: false
        default: latest

runs:
    using: composite
    steps:
        -   name: Login to Docker registry
            uses: docker/login-action@v2
            with:
                registry: ${{ inputs.registry-host }}
                username: ${{ inputs.registry-user }}
                password: ${{ inputs.registry-token }}

        -   run:    |
                export IMAGE=${{ inputs.registry-host }}/${{ inputs.registry-user }}/${{ inputs.image-name}}:${{ inputs.image-tag }}
            shell: bash

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

        -   name: Build and push
            uses: docker/build-push-action@v3
            with:
                context: ${{ inputs.content }}
                file: ${{ inputs.dockerfile }}
                push: true
                tags: $IMAGE
                cache-from: type=gha
                cache-to: type=gha,mode=max

        -   name: deploy to caprover
            run: |
                echo "Deploying to CapRover..."
                docker run caprover/cli-caprover:latest caprover deploy --host ${{inputs.server}} --pass ${{inputs.app-token}} --appName ${{inputs.app-name}} --imageName $IMAGE
            shell: bash
